-- Select data that we are going to be using.
SELECT * FROM sales_data;

-- Total Revenue : Find the total sales amount generated across all orders.
SELECT Channel, SUM(AMOUNT) AS Total_Revenue
FROM sales_data
Group by Channel;

-- Channel Performance : Find the total revenue and total quantity sold broken down by each sales channel.
SELECT Channel, SUM(Qty) AS Qty_Sold, SUM(Amount) AS Total_Revenue
FROM sales_data
Group by Channel;

-- Category Popularity : Which product category has the highest number of total orders/quantity sold
SELECT Category, SUM(Qty) AS Qty_Sold
FROM sales_data
GROUP BY Category
LIMIT 1;

-- Order status breakdown : Counting the total number of orders for each status.
SELECT status, COUNT(Qty) AS Total_Order 
FROM sales_data
GROUP BY status;

-- Top cities by revenue : finding the top 5 shipping cities generating the highest total revenue.
SELECT `ship-city`, SUM(Amount) AS Total_Revenue
FROM sales_data
Group by `ship-city` 
Order by Total_Revenue DESC
LIMIT 5;

-- Demographic analysis : Calculating the total revenue and average order amount generated by gender and age groups.
SELECT 
	Gender,
	CASE
		WHEN Age < 20 THEN '<20'
        WHEN Age BETWEEN 20 AND 30 THEN '20 - 30'
        WHEN Age BETWEEN 31 AND 40 THEN '31 - 40'
        ELSE '40 +'
        END AS Age_Group,
        SUM(Amount) AS Total_Revenue,
        Avg(Amount) AS Avg_order_amount
	FROM sales_data
    Group by Gender, Age_Group
    Order by Gender, Age_Group;

-- Daily sales : Writing a query to aggregate total sales amount and order count by Date to see daily trends.
SELECT Date, SUM(Amount) AS Total_Sales, Count(Qty) AS Total_Orders
FROM sales_data
Group by Date
Order by Date;

-- Customer purchase Ranking : Using a common table expression(CTE) and row_number , rank each customer's order chronologically by date.
WITH Ranking_Customers AS(
	SELECT `Cust ID`, Date, Amount, `Order ID`,
    Row_Number() OVER(PARTITION BY `Cust ID` Order by `Date` ASC) AS Order_Rank
FROM sales_data
)
SELECT * 
FROM Ranking_Customers;

-- Running Total : calculating a running total of revenue order by date.
WITH Daily_Revenue AS(
	SELECT Date, SUM(AMOUNT) AS Daily_Sales
FROM sales_data
Group by Date
)
SELECT 
	Date,
    Daily_Sales,
    SUM(Daily_Sales) OVER (ORDER BY Date ASC) AS Running_Total_Revenue
    FROM Daily_Revenue
    Order By Date ASC;
    
-- Second Order Per Customer : writing a query using window functions to find the second order details placed by each customer.

WITH Order_Details AS(
	SELECT
		`Order ID`,
        Amount,
        "Cust ID"
        Date,
        Channel,
        Row_Number() OVER(PARTITION BY "Cust ID" Order by Date ASC) AS Order_RANK
	FROM sales_data
)
SELECT
	`Order ID`,
    Amount,
    "Cust ID",
    Date,
    Channel
FROM Order_Details
WHERE Order_Rank = 2;
